### PR TITLE
fix brew install commands

### PR DESCRIPTION
**Pull request by ilackarms**
fix brew install commands

### CODE REVIEW

**Comment by scranton** [comment]
I personally might drop in the sidebar the prefix 'Installing Gloo ...' or 'Gloo and ...'. It's in the Gloo doc, so I'd hope users understand this is about Gloo... Just makes sidebar a little wordy for my taste

**Comment by scranton** [comment]
Upstream Function example looks wrong - https://gloo.solo.io/introduction/concepts/#functions

**Comment by rickducott** [comment]
@scranton I merged this b/c it only had 3 lines of diff with master and the updated brew command works, were your comments addressed elsewhere?

**Comment by scranton** [comment]
My comments were more about the doc title / menuTitle should not redundantly reference 'Installing Gloo ....' in the Gloo docs. Just trying to keep it DRY.

**Pull request merged**
